[package]
name = "favilib"
version = "0.1.0"
edition = "2021"



[lib]
name = "favilib"
path = "src/lib.rs"


[[bin]]
name = "favilib"
path = "src/bin.rs"

[dependencies]
anyhow = "1.0.81"
futures = "0.3.30"
image = "0.25.1"
reqwest = "0.12.3"
scraper = "0.19.0"
thiserror = "1.0.58"
tokio = {version = "1.37.0", features = ["full"]}
url = "2.5.0"
